    zn "%SYS"

    // Unexpire passwords and set up passwordless mode to simplify dev use.
    // ** Comment out these two line for Production use **
    do ##class(Security.Users).UnExpireUserPasswords("*")
    zpm "install passwordless"

    do ##class(Security.Applications).Modify("/csp/user",.prop)
    zn "USER"
    zpm "load /opt/irisbuild/ -v":1
    zpm "install webterminal -v" 
    hang 2
    halt
